Workshop 11091: Masked Lab 2 images
oracle-livelabs/goldengate pull request #40
Opened 2022-11-14 14:48 UTC by jwchan0319

11091

Masked compartment names in Lab 2 images.

2022-11-14 18:27 UTC, arabellayao requested changes
Hi! Workshop #11091's link in WMS is goldengate/mysql-ggs, and it seems like you are updating files outside of this workshop. Please add the WMS IDs of all workshops that have been updated.

2022-11-14 18:28 UTC, arabellayao commented
Your branch branch is out-of-date with the oracle-livelabs main branch. Please merge the latest changes from main into this branch.

2022-11-14 19:30 UTC, jwchan0319 commented
11091 refers to images located in ggs-common
The files for 2920 should've been included in last week's PR. I guess there's still attached to this one.

2022-11-15 01:38 UTC, arabellayao approved these changes

2022-11-15 01:38 UTC, merged